# Generated by Django 5.0.6 on 2024-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('time_remaining', models.IntegerField(default=0)),
                ('last_time_remaining_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
